name: DevPipelineiOS

variables:
  scheme: 'InAppBrowserTests'
  sdk: 'iphoneos'
  configuration: 'Debug'

pool:
  vmImage: 'macOS 10.15.5'

stages:
  - stage: Prepare plugin
    jobs:
      - job: NPM
        steps:
          - script: cd tests/ios
          - script: npm install
  - stage: Build
    jobs:
      - job: Build iOS
        steps:
          - script: ls
          - task: Xcode@5
            inputs:
              actions: 'build'
              sdk: '$(sdk)'
              scheme: '$(scheme)'
              configuration: '$(configuration)'
              xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
              xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
              exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
              packageApp: false
