parameters:
- name: scheme
  type: string
  default:
- name: configuration
  type: string
  default: Debug
- name: xcodeVersion
  type: string
  default: default
- name: workingDirectory
  type: string
  default: ${System.DefaultWorkingDirectory}
- name: destinationPlatform
  type: string
  default: iOS Simulator
- name: destinationName
  type: string
  default: iPhone 8
- name: shouldClean
  type: boolean
  default: true

jobs:
  - job: Test
    displayName: 'iOS Test'
    pool:
      vmImage: 'macOS'
    steps:
    - template: 'templates/node/npm-steps.yml'
    - task: Xcode@5
      inputs:
        ${{ if eq(parameters.shouldClean, true) }}:
          actions: 'clean build test'
        ${{ if not(eq(parameters.shouldClean, true)) }}:
          actions: 'build test'
        scheme: '${{ parameters.scheme }}'
        xcodeVersion: ${{ parameters.xcodeVersion }}
        configuration: ${{ parameters.configuration }}
        xcWorkspacePath: '${{ parameters.workingDirectory }}/**/*.xcodeproj/project.xcworkspace'
        exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
        packageApp: false
        destinationSimulators: ${{ parameters.destinationName }}
        destinationPlatform: iOS
        args: -destination "platform="${{ parameters.destinationPlatform }}",name="${{ parameters.destinationName }}
        useXcpretty: true
        publishJUnitResults: true
