name: 'InAppBrowserPlugins'
pr:
  autoCancel: false
  branches:
    include:
    - master

stages:
  - stage: Test
    jobs:
      - template: 'templates/ios-test-job.yml'
        parameters:
          scheme: 'InAppBrowserTests'
          workingDirectory: 'tests/ios'
